name: Feature Validation

on:
  workflow_run:
    workflows: ["Feature Automation"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run feature validation
        run: node .github/scripts/validate-feature.js

      - name: Run tests
        run: node .github/scripts/run-tests.js

      - name: Check test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Please check the logs."
            exit 1
          fi

      - name: Validation successful
        run: echo "Feature validation completed successfully."